# Generated by Django 3.2.1 on 2021-06-28 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poc_name', models.DateField(default=django.utils.timezone.now)),
                ('real_name', models.CharField(default='', max_length=50)),
                ('mode', models.CharField(default='', max_length=50)),
                ('risk', models.CharField(default='high', max_length=50)),
                ('hasExp', models.BooleanField(default=False)),
            ],
        ),
    ]
