# Generated by Django 3.2.1 on 2021-06-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PocModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poc',
            old_name='mode',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='poc',
            name='poc_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
