# Generated by Django 3.2.1 on 2021-06-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PocModel', '0002_auto_20210628_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='poc',
            name='isUse',
            field=models.BooleanField(default=True),
        ),
    ]
