INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (1, 'burp_sql_pwd', '数据库弱密码', '弱密码', 'danger', 0, 1, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (2, 'shiro_deserialize', 'shiro反序列化', '命令执行', 'danger', 0, 0, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (3, 'burp_tomcat', 'Tomcat弱密码', '弱密码', 'danger', 1, 0, '执行命令');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (7, 'inspur_rce', '浪潮管理系统RCE', '命令执行', 'danger', 1, 0, '执行命令');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (8, 'nc_bsh_rce', '用友OA BshServlet接口泄露', '命令执行', 'danger', 1, 0, '执行命令');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (9, 'sangfor_safe_rce', '深信服行为感知系统RCE', '命令执行', 'danger', 1, 0, '执行命令');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (10, 'safe_md5_pwd', '安全设备md5密码泄露', '弱密码', 'danger', 0, 0, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (13, 'docker', 'docker未授权', '命令执行', 'danger', 0, 0, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (14, 'thinkphp_debug', 'Thinkphp debug命令执行', '命令执行', 'danger', 1, 0, '执行命令');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (15, 'thinkphp5_rce', 'Thinkphp5命令执行', '命令执行', 'danger', 1, 0, '执行命令');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (16, 'wui_sql', '泛微OA8.0 前台SQL注入', 'SQL注入', 'warning', 0, 1, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (17, 'wui_file', '泛微OA9.0 任意文件上传', '任意文件上传', 'danger', 0, 0, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (18, 'weblogic_pwd', 'weblogic控制台弱密码', '弱密码', 'danger', 0, 0, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (19, 'weblogic_xml', 'weblogic_XML反序列化', '命令执行', 'danger', 1, 0, '上传文件');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (20, 'weblogic_wls9', 'weblogic_wls9-async反序列化', '命令执行', 'danger', 1, 0, '执行命令');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (21, 'weblogic_console_unauthorize', 'weblogic_控制台未授权访问', '垂直越权', 'warning', 0, 0, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (22, 'seeyon_webmail', '致远OA_webmail.do任意文件下载', '任意文件读取', 'warning', 1, 0, '读取文件');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (23, 'showdoc', 'ShowDoc 任意文件上传', '任意文件上传', 'danger', 1, 0, '上传文件');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (24, 'ms17_010', 'MS17_010', '命令执行', 'danger', 0, 0, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (25, 'jumpserver_logs', 'JumpServer 日志接口未授权', '垂直越权', 'warning', 0, 0, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (26, 'apache_solr_file', 'Apache Solr 任意文件读取', '任意文件读取', 'warning', 1, 0, '读取文件');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (28, 'fineport_v8_file', '帆软报表V8.0 任意文件读取', '任意文件读取', 'warning', 1, 0, '读取文件');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (29, 'minio_ssrf', 'MinIO SSRF', 'SSRF', 'warning', 0, 0, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (30, 'apache_flink_file', 'Apache Flink 任意文件读取', '任意文件读取', 'warning', 1, 0, '读取文件');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (31, 'zyxel_user', 'Zyxel 硬编码后门账户', '弱密码', 'danger', 0, 0, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (33, 'ssh_burp', 'ssh弱密码', '弱密码', 'danger', 1, 0, '执行命令');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (34, 'apache_solr_velocity', 'Apache Solr Velocity模板远程执行', '命令执行', 'danger', 1, 0, '执行命令');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (35, 'landary_file', '蓝凌OA 任意文件读取', '任意文件读取', 'danger', 1, 0, '读取文件');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (36, 'daloradius_pwd', 'daloradius弱密码', '弱密码', 'danger', 1, 0, '上传文件');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (37, 'wui_xml', '泛微OA_XML反序列化', '命令执行', 'danger', 0, 0, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (38, 'nete_firewall', '奇安信 网康下一代防火墙RCE', '命令执行', 'danger', 1, 0, '执行命令');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (39, 'vesystem_rce', '和信创天云桌面_RCE', '任意文件上传', 'danger', 1, 0, '上传文件');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (40, 'tianqin_sql', '360天擎 前台SQL注入', 'SQL注入', 'danger', 0, 0, '');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (41, 'h3c_secparth_rce', 'H3C SecParh堡垒机远程命令执行', '命令执行', 'danger', 1, 0, '执行命令');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (42, 'axis2_password', 'axis2弱密码', '弱密码', 'danger', 1, 0, '执行命令');
INSERT INTO `pocmodel_poc`(`id`, `poc_name`, `real_name`, `type`, `risk`, `hasExp`, `isUse`, `cmd`) VALUES (43, 'node_red_file', 'Node-RED 任意文件读取', '任意文件读取', 'danger', 1, 1, '读取文件');
