# Generated by Django 3.2.1 on 2021-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('ip_count', models.IntegerField(default=0)),
                ('service_process', models.FloatField(default=0)),
                ('vuln_process', models.FloatField(default=0)),
            ],
        ),
    ]
