# Generated by Django 3.2.1 on 2021-06-10 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ScanTaskModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(default=django.utils.timezone.now)),
                ('ip_count', models.IntegerField(default=0)),
                ('service_process', models.FloatField(default=0)),
                ('vuln_process', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceScan',
        ),
    ]
