# Generated by Django 3.2.1 on 2021-06-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanTaskModel', '0002_auto_20210610_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='ip_range',
            field=models.CharField(default='', max_length=50),
        ),
    ]
