# Generated by Django 3.2.1 on 2021-06-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanTaskModel', '0004_rename_ip_count_scantask_task_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='isPause',
            field=models.BooleanField(default=False),
        ),
    ]
