# Generated by Django 3.2.1 on 2021-06-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanTaskModel', '0005_scantask_ispause'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='vuln_count',
            field=models.IntegerField(default=0),
        ),
    ]
