# Generated by Django 3.2.1 on 2021-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanTaskModel', '0006_scantask_vuln_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='isStart',
            field=models.BooleanField(default=False),
        ),
    ]
