# Generated by Django 3.2.1 on 2021-06-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanTaskModel', '0007_scantask_isstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='mode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
