# Generated by Django 3.2.1 on 2021-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScanTaskModel', '0008_scantask_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
