# Generated by Django 3.2.1 on 2021-06-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VulnScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.IntegerField(default=1)),
                ('ip', models.CharField(max_length=50)),
                ('port', models.IntegerField(default=0)),
                ('vulnerability', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
