# Generated by Django 3.2.1 on 2021-06-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VulnScanModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnscan',
            name='isShown',
            field=models.BooleanField(default=False),
        ),
    ]
