# Generated by Django 3.2.1 on 2021-06-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VulnScanModel', '0002_vulnscan_isshown'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnscan',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
