# Generated by Django 3.2.1 on 2021-06-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VulnScanModel', '0003_vulnscan_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnscan',
            name='risk',
            field=models.IntegerField(default=3),
        ),
    ]
