# Generated by Django 3.2.1 on 2021-06-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VulnScanModel', '0004_vulnscan_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnscan',
            name='risk',
            field=models.CharField(default='danger', max_length=10),
        ),
    ]
