# Generated by Django 3.2.1 on 2021-06-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VulnScanModel', '0005_alter_vulnscan_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnscan',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
