# Generated by Django 3.2.1 on 2021-07-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VulnScanModel', '0006_alter_vulnscan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnscan',
            name='module',
            field=models.CharField(default='', max_length=50),
        ),
    ]
