# Generated by Django 3.2.1 on 2021-07-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VulnScanModel', '0007_vulnscan_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnscan',
            name='specify',
            field=models.CharField(default='', max_length=50),
        ),
    ]
