# Generated by Django 3.2.1 on 2021-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceScanModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicescan',
            name='isActive',
        ),
        migrations.AddField(
            model_name='servicescan',
            name='isShown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicescan',
            name='taskid',
            field=models.IntegerField(default=1),
        ),
    ]
