# Generated by Django 3.2.1 on 2021-06-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceScanModel', '0002_auto_20210610_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescan',
            name='type',
            field=models.CharField(default='low', max_length=50),
        ),
    ]
