# Generated by Django 3.2.1 on 2021-06-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceScanModel', '0003_servicescan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescan',
            name='server',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicescan',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
