# Generated by Django 3.2.1 on 2021-07-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceScanModel', '0004_auto_20210611_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescan',
            name='vulnerable',
            field=models.BooleanField(default=False),
        ),
    ]
