# Generated by Django 3.2.1 on 2021-07-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceScanModel', '0005_servicescan_vulnerable'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescan',
            name='note',
            field=models.CharField(default='', max_length=100),
        ),
    ]
